services:
  web:
    build:
      context: ../labassist-web/
      dockerfile: ./compose/local/react/Dockerfile
      args:
        VITE_API_ENDPOINT: /api/
    image: chronovortex07/react-web
    container_name: react-web
    ports:
      - "3000:3000"
    depends_on:
      - api
      - redis
      - celery-worker

  api:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    image: chronovortex07/flask-api
    container_name: flask-api
    ports:
      - "5500:5500"
    environment:
      DEBUG_MODE: True
      UPLOAD_FOLDER: /uploads
      CLEANUP_UPLOADS: False
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_TASK_TRACK_STARTED: True
      CELERY_TRACK_STARTED: True
      SOCKETIO_MESSAGE_QUEUE: redis://redis:6379/1
      VIDEO_JSON_PATH: "/app/videos.json"
      SECRET_KEY: "secret"
      ACTION_MODEL_PATH: "/app/app/ml_models/action_detection/weights/model-v1.pth"
      OBJECT_MODEL_PATH: "/app/app/ml_models/object_detection/weights/obj_detect_best_v5.pt"
      NVIDIA_DISABLE_REQUIRE: 1
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    volumes:
      - ./uploads:/uploads
    depends_on:
      - redis
      - celery-worker

  celery-worker:
    build:
      context: .
      dockerfile: ./compose/local/celery/worker/Dockerfile
    image: chronovortex07/celery-worker
    container_name: celery-worker
    environment:
      DEBUG_MODE: True
      UPLOAD_FOLDER: /uploads
      CLEANUP_UPLOADS: False
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_TASK_TRACK_STARTED: True
      CELERY_TRACK_STARTED: True
      SOCKETIO_MESSAGE_QUEUE: redis://redis:6379/1
      VIDEO_JSON_PATH: "/app/videos.json"
      SECRET_KEY: "secret"
      ACTION_MODEL_PATH: "/app/app/ml_models/action_detection/weights/model-v1.pth"
      OBJECT_MODEL_PATH: "/app/app/ml_models/object_detection/weights/obj_detect_best_v5.pt"
      NVIDIA_DISABLE_REQUIRE: 1
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    runtime: nvidia
    volumes:
      - ./uploads:/uploads
    depends_on:
      - redis

  redis:
    image: "redis:bullseye"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./compose/local/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - api
      - celery-worker
      - redis